# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
#   branches:
#     include:
#     - master
#   paths:
#     exclude:
#     - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: HMZ-Software

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'run'
#     projects: 'MarkupCompiler/*.csproj'
#     arguments: '$(TargetDir)MarkupCompiler.exe'
